online-mode=false
view-distance=32
simulation-distance=10
difficulty=normal
gamemode=survival
max-players=20
motd=On-demand vanilla server
enable-command-block=true
spawn-protection=0
allow-flight=false
white-list=false
pvp=true
